// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Summarizes a user's progress on their goals for the week.
 *
 * - summarizeGoalProgress - A function that generates a summary of a user's progress on their goals.
 * - SummarizeGoalProgressInput - The input type for the summarizeGoalProgress function.
 * - SummarizeGoalProgressOutput - The return type for the summarizeGoalProgress function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeGoalProgressInputSchema = z.object({
  goal: z.string().describe('The goal the user is tracking.'),
  progressUpdates: z
    .array(z.string())
    .describe('A list of progress updates for the week.'),
});
export type SummarizeGoalProgressInput = z.infer<typeof SummarizeGoalProgressInputSchema>;

const SummarizeGoalProgressOutputSchema = z.object({
  summary: z.string().describe('A one-sentence summary of the user\'s progress.'),
});
export type SummarizeGoalProgressOutput = z.infer<typeof SummarizeGoalProgressOutputSchema>;

export async function summarizeGoalProgress(
  input: SummarizeGoalProgressInput
): Promise<SummarizeGoalProgressOutput> {
  return summarizeGoalProgressFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeGoalProgressPrompt',
  input: {schema: SummarizeGoalProgressInputSchema},
  output: {schema: SummarizeGoalProgressOutputSchema},
  prompt: `Summarize the user's progress on their goal in one sentence.

Goal: {{{goal}}}
Progress Updates:
{{#each progressUpdates}}- {{{this}}}
{{/each}}
`,
});

const summarizeGoalProgressFlow = ai.defineFlow(
  {
    name: 'summarizeGoalProgressFlow',
    inputSchema: SummarizeGoalProgressInputSchema,
    outputSchema: SummarizeGoalProgressOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
